version: 2

project_name: poke-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: poke-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version=v2.0.0
  - id: poke-cache
    builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: poke-cache
    prebuilt:
      path: prebuilt/poke-cache-{{ .Os }}-{{ .Arch }}/poke-cache{{ .Ext }}

archives:
  - id: poke-cli
    ids: [ poke-cli, poke-cache ]
    formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: poke-cache
    ids: [ poke-cache ]
    formats: [ 'zip' ]
    name_template: >-
      poke-cache_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: poke-cli
    ids: [ poke-cli ]
    description: "A hybrid CLI/TUI tool written in Go for viewing Pokémon data from the terminal!"
    homepage: "https://docs.poke-cli.com/"
    license: MIT
    repository:
      owner: digitalghost-dev
      name: homebrew-tap
      token: "{{.Env.GITHUB_TOKEN}}"
    hooks:
      post:
        install: |
          if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
          end

scoops:
  - name: poke-cli
    ids: [ poke-cli ]
    description: "A hybrid CLI/TUI tool written in Go for viewing Pokémon data from the terminal!"
    homepage: "https://docs.poke-cli.com/"
    license: MIT
    repository:
      owner: digitalghost-dev
      name: scoop-bucket
      token: "{{ .Env.GITHUB_TOKEN }}"
