-- -- scripts/create_berries.sql
CREATE TABLE berries (
    id INTEGER PRIMARY KEY,
    name TEXT NULL UNIQUE,
    effect TEXT NULL,
    firmness TEXT NULL,
    growth_time INTEGER NULL,
    max_harvest INTEGER NULL,
    natural_gift_power INTEGER NULL,
    natural_gift_type TEXT NULL,
    size INTEGER NULL,
    smoothness INTEGER NULL,
    soil_dryness INTEGER NULL,
    sprite_url TEXT NULL
);

CREATE TABLE berry_flavors (
    berry_id INTEGER NOT NULL,
    flavor_name TEXT NOT NULL,
    potency INTEGER NOT NULL,
    FOREIGN KEY (berry_id) REFERENCES berries(id)
);

INSERT INTO berries VALUES
    (1, 'cheri', 'When paralyzed, cures paralysis', 'soft', 3, 5, 60, 'fire', 20, 25, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/cheri-berry.png'),
    (2, 'chesto', 'When asleep, cures sleeping', 'super-hard', 3, 5, 60, 'water', 80, 25, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/chesto-berry.png'),
    (3, 'pecha', 'When poisoned, cures poison', 'very-soft', 3, 5, 60, 'electric', 40, 25, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pecha-berry.png'),
    (4, 'rawst', 'When burned, cures burn', 'hard', 3, 5, 60, 'grass', 32, 25, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rawst-berry.png'),
    (5, 'aspear', 'When frozen, cures freeze', 'super-hard', 3, 5, 60, 'ice', 50, 25, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aspear-berry.png'),
    (6, 'leppa', 'When one move reaches 0 PP, restores 10 PP of the move', 'very-hard', 4, 5, 60, 'fighting', 28, 20, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leppa-berry.png'),
    (7, 'oran', 'When holder has less than ½ of their max HP, restores 10 HP', 'super-hard', 4, 5, 60, 'poison', 35, 20, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/oran-berry.png'),
    (8, 'persim', 'When confused, cures confusion', 'hard', 4, 5, 60, 'ground', 47, 20, 15, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/persim-berry.png'),
    (9, 'lum', 'When holder has a status effect or confusion, cures the status effect', 'super-hard', 12, 5, 60, 'flying', 34, 20, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lum-berry.png'),
    (10, 'sitrus', 'When holder has less than ½ of their max HP, restores ¼ of max HP', 'very-hard', 8, 5, 60, 'psychic', 95, 20, 7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sitrus-berry.png'),
    (11, 'figy', 'When holder has less than ¼ of their max HP, restores ⅓ of max HP, but confuses the holder if it dislikes the spicy flavor', 'soft', 5, 5, 60, 'bug', 100, 25, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/figy-berry.png'),
    (12, 'wiki', 'When holder has less than ¼ of their max HP, restores ⅓ of max HP, but confuses the holder if it dislikes the dry flavor', 'hard', 5, 5, 60, 'rock', 115, 25, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wiki-berry.png'),
    (13, 'mago', 'When holder has less than ¼ of their max HP, restores ⅓ of max HP, but confuses the holder if it dislikes the sweet flavor', 'hard', 5, 5, 60, 'ghost', 126, 25, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mago-berry.png'),
    (14, 'aguav', 'When holder has less than ¼ of their max HP, restores ⅓ of max HP, but confuses the holder if it dislikes the bitter flavor', 'super-hard', 5, 5, 60, 'dragon', 64, 25, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/aguav-berry.png'),
    (15, 'iapapa', 'When holder has less than ¼ of their max HP, restores ⅓ of max HP, but confuses the holder if it dislikes the sour flavor', 'soft', 5, 5, 60, 'dark', 223, 25, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/iapapa-berry.png'),
    (16, 'razz', 'Makes wild Pokémon easier to catchPE', 'very-hard', 2, 10, 60, 'steel', 120, 20, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razz-berry.png'),
    (17, 'bluk', '', 'soft', 2, 10, 70, 'fire', 108, 20, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/bluk-berry.png'),
    (18, 'nanab', 'Makes wild Pokémon move lessPE', 'very-hard', 2, 10, 70, 'water', 77, 20, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nanab-berry.png'),
    (19, 'wepear', '', 'super-hard', 2, 10, 70, 'electric', 74, 20, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wepear-berry.png'),
    (20, 'pinap', 'Increases item drops after capturePE', 'hard', 2, 10, 70, 'grass', 80, 20, 35, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pinap-berry.png'),
    (21, 'pomeg', 'Increases friendship but lowers HP EVE+', 'very-hard', 8, 5, 70, 'ice', 135, 20, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pomeg-berry.png'),
    (22, 'kelpsy', 'Increases friendship but lowers Attack EVE+', 'hard', 8, 5, 70, 'fighting', 150, 20, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kelpsy-berry.png'),
    (23, 'qualot', 'Increases friendship but lowers Defense EVE+', 'hard', 8, 5, 70, 'poison', 110, 20, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/qualot-berry.png'),
    (24, 'hondew', 'Increases friendship but lowers Sp. Atk EVE+', 'hard', 8, 5, 70, 'ground', 162, 20, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/hondew-berry.png'),
    (25, 'grepa', 'Increases friendship but lowers Sp. Def EVE+', 'soft', 8, 5, 70, 'flying', 149, 20, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/grepa-berry.png'),
    (26, 'tamato', 'Increases friendship but lowers Speed EVE+', 'soft', 8, 5, 70, 'psychic', 200, 30, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tamato-berry.png'),
    (27, 'cornn', '', 'hard', 6, 10, 70, 'bug', 75, 30, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/cornn-berry.png'),
    (28, 'magost', '', 'hard', 6, 10, 70, 'rock', 140, 30, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/magost-berry.png'),
    (29, 'rabuta', '', 'soft', 6, 10, 70, 'ghost', 226, 30, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rabuta-berry.png'),
    (30, 'nomel', '', 'super-hard', 6, 10, 70, 'dragon', 285, 30, 10, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/nomel-berry.png'),
    (31, 'spelon', '', 'soft', 15, 15, 70, 'dark', 133, 35, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/spelon-berry.png'),
    (32, 'pamtre', '', 'very-soft', 15, 15, 70, 'steel', 244, 35, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pamtre-berry.png'),
    (33, 'watmel', '', 'soft', 15, 15, 80, 'fire', 250, 35, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/watmel-berry.png'),
    (34, 'durin', '', 'hard', 15, 15, 80, 'water', 280, 35, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/durin-berry.png'),
    (35, 'belue', '', 'very-soft', 15, 15, 80, 'electric', 300, 35, 8, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/belue-berry.png'),
    (36, 'occa', 'When holder is hit by a supereffective Fire-type move, halves the damage', 'super-hard', 18, 5, 60, 'fire', 90, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/occa-berry.png'),
    (37, 'passho', 'When holder is hit by a supereffective Water-type move, halves the damage', 'soft', 18, 5, 60, 'water', 33, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/passho-berry.png'),
    (38, 'wacan', 'When holder is hit by a supereffective Electric-type move, halves the damage', 'very-soft', 18, 5, 60, 'electric', 250, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wacan-berry.png'),
    (39, 'rindo', 'When holder is hit by a supereffective Grass-type move, halves the damage', 'soft', 18, 5, 60, 'grass', 156, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rindo-berry.png'),
    (40, 'yache', 'When holder is hit by a supereffective Ice-type move, halves the damage', 'very-hard', 18, 5, 60, 'ice', 135, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/yache-berry.png'),
    (41, 'chople', 'When holder is hit by a supereffective Fighting-type move, halves the damage', 'soft', 18, 5, 60, 'fighting', 77, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/chople-berry.png'),
    (42, 'kebia', 'When holder is hit by a supereffective Poison-type move, halves the damage', 'hard', 18, 5, 60, 'poison', 90, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kebia-berry.png'),
    (43, 'shuca', 'When holder is hit by a supereffective Ground-type move, halves the damage', 'soft', 18, 5, 60, 'ground', 42, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shuca-berry.png'),
    (44, 'coba', 'When holder is hit by a supereffective Flying-type move, halves the damage', 'very-hard', 18, 5, 60, 'flying', 278, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/coba-berry.png'),
    (45, 'payapa', 'When holder is hit by a supereffective Psychic-type move, halves the damage', 'soft', 18, 5, 60, 'psychic', 252, 30, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/payapa-berry.png'),
    (46, 'tanga', 'When holder is hit by a supereffective Bug-type move, halves the damage', 'very-soft', 18, 5, 60, 'bug', 42, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tanga-berry.png'),
    (47, 'charti', 'When holder is hit by a supereffective Rock-type move, halves the damage', 'very-soft', 18, 5, 60, 'rock', 28, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/charti-berry.png'),
    (48, 'kasib', 'When holder is hit by a supereffective Ghost-type move, halves the damage', 'hard', 18, 5, 60, 'ghost', 144, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/kasib-berry.png'),
    (49, 'haban', 'When holder is hit by a supereffective Dragon-type move, halves the damage', 'soft', 18, 5, 60, 'dragon', 23, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/haban-berry.png'),
    (50, 'colbur', 'When holder is hit by a supereffective Dark-type move, halves the damage', 'super-hard', 18, 5, 60, 'dark', 39, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/colbur-berry.png'),
    (51, 'babiri', 'When holder is hit by a supereffective Steel-type move, halves the damage', 'super-hard', 18, 5, 60, 'steel', 265, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/babiri-berry.png'),
    (52, 'chilan', 'When holder is hit by a Normal-type move, halves the damage', 'very-soft', 18, 5, 60, 'normal', 34, 35, 6, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/chilan-berry.png'),
    (53, 'liechi', 'When holder has less than ¼ of their max HP, raises Attack', 'very-hard', 24, 5, 80, 'grass', 111, 40, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/liechi-berry.png'),
    (54, 'ganlon', 'When holder has less than ¼ of their max HP, raises Defense', 'very-hard', 24, 5, 80, 'ice', 33, 40, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/ganlon-berry.png'),
    (55, 'salac', 'When holder has less than ¼ of their max HP, raises Speed', 'very-hard', 24, 5, 80, 'fighting', 95, 40, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/salac-berry.png'),
    (56, 'petaya', 'When holder has less than ¼ of their max HP, raises Sp. Atk', 'very-hard', 24, 5, 80, 'poison', 237, 40, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/petaya-berry.png'),
    (57, 'apicot', 'When holder has less than ¼ of their max HP, raises Sp. Def', 'hard', 24, 5, 80, 'ground', 75, 40, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/apicot-berry.png'),
    (58, 'lansat', 'When holder has less than ¼ of their max HP, raises critical-hit ratio', 'soft', 24, 5, 80, 'flying', 97, 50, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lansat-berry.png'),
    (59, 'starf', 'When holder has less than ¼ of their max HP, raises a random stat', 'super-hard', 24, 5, 80, 'psychic', 153, 50, 4, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/starf-berry.png'),
    (60, 'enigma', 'When holder is hit by a supereffective move, raises ¼ of their max HP', 'hard', 24, 5, 80, 'bug', 155, 60, 7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/enigma-berry.png'),
    (61, 'micle', 'When holder has less than ¼ their max HP, raises accuracy of next move', 'soft', 24, 5, 80, 'rock', 41, 60, 7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/micle-berry.png'),
    (62, 'custap', 'When holder has less than ¼ their max HP, holder will go first for the next turn', 'super-hard', 24, 5, 80, 'ghost', 267, 60, 7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/custap-berry.png'),
    (63, 'jaboca', 'When holder is hit by a physical move, attacker is also hurt', 'soft', 24, 5, 80, 'dragon', 33, 60, 7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/jaboca-berry.png'),
    (64, 'rowap', 'When holder is hit by a special move, attacker is also hurt', 'very-soft', 24, 5, 80, 'dark', 52, 60, 7, 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rowap-berry.png');

-- Berry flavors data
INSERT INTO berry_flavors VALUES
    (1, 'spicy', 10),
    (1, 'dry', 0),
    (1, 'sweet', 0),
    (1, 'bitter', 0),
    (1, 'sour', 0),
    (2, 'spicy', 0),
    (2, 'dry', 10),
    (2, 'sweet', 0),
    (2, 'bitter', 0),
    (2, 'sour', 0),
    (3, 'spicy', 0),
    (3, 'dry', 0),
    (3, 'sweet', 10),
    (3, 'bitter', 0),
    (3, 'sour', 0),
    (4, 'spicy', 0),
    (4, 'dry', 0),
    (4, 'sweet', 0),
    (4, 'bitter', 10),
    (4, 'sour', 0),
    (5, 'spicy', 0),
    (5, 'dry', 0),
    (5, 'sweet', 0),
    (5, 'bitter', 0),
    (5, 'sour', 10),
    (6, 'spicy', 10),
    (6, 'dry', 0),
    (6, 'sweet', 10),
    (6, 'bitter', 10),
    (6, 'sour', 10),
    (7, 'spicy', 10),
    (7, 'dry', 10),
    (7, 'sweet', 0),
    (7, 'bitter', 10),
    (7, 'sour', 10),
    (8, 'spicy', 10),
    (8, 'dry', 10),
    (8, 'sweet', 10),
    (8, 'bitter', 0),
    (8, 'sour', 10),
    (9, 'spicy', 10),
    (9, 'dry', 10),
    (9, 'sweet', 10),
    (9, 'bitter', 10),
    (9, 'sour', 0),
    (10, 'spicy', 0),
    (10, 'dry', 10),
    (10, 'sweet', 10),
    (10, 'bitter', 10),
    (10, 'sour', 10),
    (11, 'spicy', 15),
    (11, 'dry', 0),
    (11, 'sweet', 0),
    (11, 'bitter', 0),
    (11, 'sour', 0),
    (12, 'spicy', 0),
    (12, 'dry', 15),
    (12, 'sweet', 0),
    (12, 'bitter', 0),
    (12, 'sour', 0),
    (13, 'spicy', 0),
    (13, 'dry', 0),
    (13, 'sweet', 15),
    (13, 'bitter', 0),
    (13, 'sour', 0),
    (14, 'spicy', 0),
    (14, 'dry', 0),
    (14, 'sweet', 0),
    (14, 'bitter', 15),
    (14, 'sour', 0),
    (15, 'spicy', 0),
    (15, 'dry', 0),
    (15, 'sweet', 0),
    (15, 'bitter', 0),
    (15, 'sour', 15),
    (16, 'spicy', 10),
    (16, 'dry', 10),
    (16, 'sweet', 0),
    (16, 'bitter', 0),
    (16, 'sour', 0),
    (17, 'spicy', 0),
    (17, 'dry', 10),
    (17, 'sweet', 10),
    (17, 'bitter', 0),
    (17, 'sour', 0),
    (18, 'spicy', 0),
    (18, 'dry', 0),
    (18, 'sweet', 10),
    (18, 'bitter', 10),
    (18, 'sour', 0),
    (19, 'spicy', 0),
    (19, 'dry', 0),
    (19, 'sweet', 0),
    (19, 'bitter', 10),
    (19, 'sour', 10),
    (20, 'spicy', 10),
    (20, 'dry', 0),
    (20, 'sweet', 0),
    (20, 'bitter', 0),
    (20, 'sour', 10),
    (21, 'spicy', 10),
    (21, 'dry', 0),
    (21, 'sweet', 10),
    (21, 'bitter', 10),
    (21, 'sour', 0),
    (22, 'spicy', 0),
    (22, 'dry', 10),
    (22, 'sweet', 0),
    (22, 'bitter', 10),
    (22, 'sour', 10),
    (23, 'spicy', 10),
    (23, 'dry', 0),
    (23, 'sweet', 10),
    (23, 'bitter', 0),
    (23, 'sour', 10),
    (24, 'spicy', 10),
    (24, 'dry', 10),
    (24, 'sweet', 0),
    (24, 'bitter', 10),
    (24, 'sour', 0),
    (25, 'spicy', 0),
    (25, 'dry', 10),
    (25, 'sweet', 10),
    (25, 'bitter', 0),
    (25, 'sour', 10),
    (26, 'spicy', 20),
    (26, 'dry', 10),
    (26, 'sweet', 0),
    (26, 'bitter', 0),
    (26, 'sour', 0),
    (27, 'spicy', 0),
    (27, 'dry', 20),
    (27, 'sweet', 10),
    (27, 'bitter', 0),
    (27, 'sour', 0),
    (28, 'spicy', 0),
    (28, 'dry', 0),
    (28, 'sweet', 20),
    (28, 'bitter', 10),
    (28, 'sour', 0),
    (29, 'spicy', 0),
    (29, 'dry', 0),
    (29, 'sweet', 0),
    (29, 'bitter', 20),
    (29, 'sour', 10),
    (30, 'spicy', 10),
    (30, 'dry', 0),
    (30, 'sweet', 0),
    (30, 'bitter', 0),
    (30, 'sour', 20),
    (31, 'spicy', 30),
    (31, 'dry', 10),
    (31, 'sweet', 0),
    (31, 'bitter', 0),
    (31, 'sour', 0),
    (32, 'spicy', 0),
    (32, 'dry', 30),
    (32, 'sweet', 10),
    (32, 'bitter', 0),
    (32, 'sour', 0),
    (33, 'spicy', 0),
    (33, 'dry', 0),
    (33, 'sweet', 30),
    (33, 'bitter', 10),
    (33, 'sour', 0),
    (34, 'spicy', 0),
    (34, 'dry', 0),
    (34, 'sweet', 0),
    (34, 'bitter', 30),
    (34, 'sour', 10),
    (35, 'spicy', 10),
    (35, 'dry', 0),
    (35, 'sweet', 0),
    (35, 'bitter', 0),
    (35, 'sour', 30),
    (36, 'spicy', 15),
    (36, 'dry', 0),
    (36, 'sweet', 10),
    (36, 'bitter', 0),
    (36, 'sour', 0),
    (37, 'spicy', 0),
    (37, 'dry', 15),
    (37, 'sweet', 0),
    (37, 'bitter', 10),
    (37, 'sour', 0),
    (38, 'spicy', 0),
    (38, 'dry', 0),
    (38, 'sweet', 15),
    (38, 'bitter', 0),
    (38, 'sour', 10),
    (39, 'spicy', 10),
    (39, 'dry', 0),
    (39, 'sweet', 0),
    (39, 'bitter', 15),
    (39, 'sour', 0),
    (40, 'spicy', 0),
    (40, 'dry', 10),
    (40, 'sweet', 0),
    (40, 'bitter', 0),
    (40, 'sour', 15),
    (41, 'spicy', 15),
    (41, 'dry', 0),
    (41, 'sweet', 0),
    (41, 'bitter', 10),
    (41, 'sour', 0),
    (42, 'spicy', 0),
    (42, 'dry', 15),
    (42, 'sweet', 0),
    (42, 'bitter', 0),
    (42, 'sour', 10),
    (43, 'spicy', 10),
    (43, 'dry', 0),
    (43, 'sweet', 15),
    (43, 'bitter', 0),
    (43, 'sour', 0),
    (44, 'spicy', 0),
    (44, 'dry', 10),
    (44, 'sweet', 0),
    (44, 'bitter', 15),
    (44, 'sour', 0),
    (45, 'spicy', 0),
    (45, 'dry', 0),
    (45, 'sweet', 10),
    (45, 'bitter', 0),
    (45, 'sour', 15),
    (46, 'spicy', 20),
    (46, 'dry', 0),
    (46, 'sweet', 0),
    (46, 'bitter', 0),
    (46, 'sour', 10),
    (47, 'spicy', 10),
    (47, 'dry', 20),
    (47, 'sweet', 0),
    (47, 'bitter', 0),
    (47, 'sour', 0),
    (48, 'spicy', 0),
    (48, 'dry', 10),
    (48, 'sweet', 20),
    (48, 'bitter', 0),
    (48, 'sour', 0),
    (49, 'spicy', 0),
    (49, 'dry', 0),
    (49, 'sweet', 10),
    (49, 'bitter', 20),
    (49, 'sour', 0),
    (50, 'spicy', 0),
    (50, 'dry', 0),
    (50, 'sweet', 0),
    (50, 'bitter', 10),
    (50, 'sour', 20),
    (51, 'spicy', 25),
    (51, 'dry', 10),
    (51, 'sweet', 0),
    (51, 'bitter', 0),
    (51, 'sour', 0),
    (52, 'spicy', 0),
    (52, 'dry', 25),
    (52, 'sweet', 10),
    (52, 'bitter', 0),
    (52, 'sour', 0),
    (53, 'spicy', 30),
    (53, 'dry', 10),
    (53, 'sweet', 30),
    (53, 'bitter', 0),
    (53, 'sour', 0),
    (54, 'spicy', 0),
    (54, 'dry', 30),
    (54, 'sweet', 10),
    (54, 'bitter', 30),
    (54, 'sour', 0),
    (55, 'spicy', 0),
    (55, 'dry', 0),
    (55, 'sweet', 30),
    (55, 'bitter', 10),
    (55, 'sour', 30),
    (56, 'spicy', 30),
    (56, 'dry', 0),
    (56, 'sweet', 0),
    (56, 'bitter', 30),
    (56, 'sour', 10),
    (57, 'spicy', 10),
    (57, 'dry', 30),
    (57, 'sweet', 0),
    (57, 'bitter', 0),
    (57, 'sour', 30),
    (58, 'spicy', 30),
    (58, 'dry', 10),
    (58, 'sweet', 30),
    (58, 'bitter', 10),
    (58, 'sour', 30),
    (59, 'spicy', 30),
    (59, 'dry', 10),
    (59, 'sweet', 30),
    (59, 'bitter', 10),
    (59, 'sour', 30),
    (60, 'spicy', 40),
    (60, 'dry', 10),
    (60, 'sweet', 0),
    (60, 'bitter', 0),
    (60, 'sour', 0),
    (61, 'spicy', 0),
    (61, 'dry', 40),
    (61, 'sweet', 10),
    (61, 'bitter', 0),
    (61, 'sour', 0),
    (62, 'spicy', 0),
    (62, 'dry', 0),
    (62, 'sweet', 40),
    (62, 'bitter', 10),
    (62, 'sour', 0),
    (63, 'spicy', 0),
    (63, 'dry', 0),
    (63, 'sweet', 0),
    (63, 'bitter', 40),
    (63, 'sour', 10),
    (64, 'spicy', 10),
    (64, 'dry', 0),
    (64, 'sweet', 0),
    (64, 'bitter', 0),
    (64, 'sour', 40);
