data_source supabase:
  type: postgres
  connection:
    host: aws-0-us-east-2.pooler.supabase.com
    port: '5432'
    username: ${SUPABASE_USER}
    password: ${SUPABASE_PASSWORD}
    database: postgres
    schema: staging
